# Generated by Django 5.1.2 on 2024-10-25 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='serial_carroceria',
            new_name='serial',
        ),
    ]
